spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:prod_host}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
openai:
  base-url: https://api.openai.com/v1
  chatCompletionsEndpoint: /chat/completions
discord:
  api-key: ${OPENAI_API_KEY_FOR_DISCORD}
  max-tokens: ${MAX_TOKENS_OPEN_AI_FOR_DISCORD}
  open-ai-model: ${OPEN_AI_MODEL_FOR_DISCORD}
  bot-token: ${DISCORD_BOT_TOKEN}
  bot-prefix: "!ai "
  bot-enabled: true
jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}
  refreshExpirationDays: ${JWT_REFRESH_EXPIRATION_DAYS}
encryption:
  key: ${ENCRYPTION_KEY}
  salt: ${SALT}

